name: SecretFlow Feature Request Template
description: To request a new feature
title: "[Feature]: "
body:
  - type: dropdown
    id: issue-type
    attributes:
      label: Feature Request Type
      description: What kind of feature would you like to request?
      multiple: false
      options:
        - Build/Install
        - Performance
        - Support
        - Usability
        - Documentation
        - Currentness/Accuracy
        - Others
    validations:
      required: true
  - type: dropdown
    id: search-check
    attributes:
      label: Have you searched existing issues?
      description: To prevent duplicated reports, it is strongly suggested that you search existing issues first.
      options: ['Yes', 'No']
    validations:
      required: true
  - type: textarea
    id: justification
    attributes:
      label: Justification for the Feature
      value: Please provide a reason why you want to add this feature.
    validations:
      required: true
  - type: textarea
    id: proposed-feature
    attributes:
      label: Proposed Feature Description
      value: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions Considered
      value: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true