# application configurations.
applications:
  # which target to run (train/attack/auto).
  mode: train
  # which dataset to run (all/bank/...)
  dataset: all
  # which model to run (all/bank/...)
  model: all
  # which attack to run (all/bank/...)
  attack: all
  # whether to run a simple test with small dataset and small epoch.
  simple: false
  # whether to use gpu to accelerate.
  use_gpu: false
  # whether using debug mode to run sf or not
  debug_mode: true
paths:
  # the dataset store path, you can put the datasets here, or will auto download.
  datasets: ~
  # the autoattack result store path.
  autoattack_path: ~
resources:
  # how many CPUs do all your machines add up to.
  num_cpus: ~
  # how many CPUs do all your machines add up to (need applications.use_gpu = true).
  num_gpus: ~
